#ifndef DSL_LIB_H
#define DSL_LIB_H

#include "graphic_type.h"

#define XXX constexpr GK_ID
XXX GK_INIT_FON_VID = 0;
XXX GK_INIT_TEXT = 1;

XXX GK_START_GUESS_FON_VID = 2;
XXX GK_START_GUESS_MAIN_TEXT = 3;
XXX GK_START_GUESS_GET_ADMIN_BUTTON = 4;
XXX GK_START_GUESS_BEGIN_BUTTON = 5;
XXX GK_START_GUESS_EXIT_BUTTON = 6;

XXX GK_GUESS_FON_VID = 7;
XXX GK_GUESS_YES_BUTTON = 8;
XXX GK_GUESS_NO_BUTTON = 9;
XXX GK_GUESS_MAIN_TEXT = 10;
XXX GK_GUESS_IMAGE = 11;

XXX GK_SUCCESS_FON_VID = 12;
XXX GK_SUCCESS_RETURN_BUTTON = 13;
XXX GK_SUCCESS_MAIN_TEXT = 14;
XXX GK_SUCCESS_IMAGE = 12;

XXX GK_N_SUCCESS_FON_VID = 15;
XXX GK_N_SUCCESS_MAIN_TEXT = 16;
XXX GK_N_SUCCESS_PASSWORD_TEXT = 17;
XXX GK_N_SUCCESS_RETURN_BUTTON = 18;
XXX GK_N_SUCCESS_IMAGE = 19;

XXX GK_MENU_INIT = 0;
XXX GK_MENU_START_GUESS = 1;
XXX GK_MENU_GUESS = 2;
XXX GK_MENU_SUCCESS = 3;
XXX GK_MENU_N_SUCCESS = 4;
XXX GK_MENU_ADMIN_MENU = 5;
XXX GK_MENU_EXIT_MENU = 6;

// XXX GK_N_SUCCESS_FON_IMG = 15;
// XXX GK_N_SUCCESS_ADD_BUTTON = 16;
// XXX GK_N_

#undef XXX

#endif /* DSL_LIB_H */
