# 0     Background
image {
    rect 0 0 1280 720
    data "Data/Img/back.png"
}



button {
    rect    10 20 100 60
    tex_p  "Data/Img/3.png"
    tex_u  "Data/Img/4.png"
    data    "Exit"
    action 2
}
# image {
#     rect 0 0 1280 720
#     data "Data/Img/1.png"
# }
text {
    rect    100 500 500 200
    kind    output
    tex     "Data/Img/2.png"
    data    "Приветствую"
}
# video {
#     rect    100 200 1000 400
#     data    8 "Data/Vid/Back"
#     delay   200
# }
