# Init Menu (0)
|0 1 2 3|

# Start Guess (1)
|0 4 9 10|

# Guess (2)
|0 4 5 6|

# Success (3)
|0 4 7 8|

# Not Success (4)
|0 4|

# Admin Menu (5)
|0 4 11 12 13|

# Add Menu (6)
|0|

# Exit Menu (7)
|0|
