# 0     Init Text
text {
    rect    340 200 600 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "Привествуем игрока в игре Акинатор$Вы хотите начать?"
}

# 1     Start Play Text
text {
    rect    340 200 600 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "Привествуем игрока в игре Акинатор$Вы хотите начать? 2"
}

# 2     Start Play Text
text {
    rect    340 200 600 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "Тут что то есть"
}

# 3     View Text
text {
    rect    340 200 600 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "Тут что то есть 1"
}

# 4     Choice Text
text {
    rect    340 200 600 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "Тут что то есть 2"
}

# 5     Exit Text
text {
    rect    340 200 600 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "Тут что то есть 3"
}

# 6     Init Img
image {
    rect 0 0 1280 720
    data "Data/Img/1.png"
}

# 7     Start Play Img
image {
    rect 0 0 1280 720
    data "Data/Img/1.png"
}

# 8     View Img
image {
    rect 0 0 1280 720
    data "Data/Img/1.png"
}

# 9     Choice Img
image {
    rect 0 0 1280 720
    data "Data/Img/1.png"
}

# 10    Choice 0 Button
button {
    rect    650 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Добавить объект"
    action 6
}

# 11    Choice 1 Button
button {
    rect    650 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Добавить объект"
    action 7
}

# 12    Choice 2 Button
button {
    rect    650 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Добавить объект"
    action 8
}

# 13    Choice 3 Button
button {
    rect    650 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Добавить объект"
    action 9
}

# 14    Background
image {
    rect 0 0 1280 720
    data "Data/Img/back.png"
}

# 15    Start Button
button {
    rect    650 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Начать игру"
    action  1
}

# 16    Exit Button
button {
    rect   100 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Выйти из игры"
    action   3
}

# 17    Skip Button
button {
    rect   100 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Продолжить"
    action   4
}

# 15    Start Button
button {
    rect    650 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Начать игру"
    action  1
}
