# 0     Background
image {
    rect 0 0 1280 720
    data "Data/Img/back.png"
}

# 1     Init Text
text {
    rect    340 200 600 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "Привествуем игрока в игре Акинатор$Вы хотите начать?"
}

# 2     Init Button Start
button {
    rect    340 500 300 100
    tex_p  "Data/Img/but_pr.png"
    tex_u  "Data/Img/but_un.png"
    data    "Начать игру"
    action 1
}

# 3     Init Button Exit
button {
    rect    650 500 300 100
    tex_p  "Data/Img/but_pr.png"
    tex_u  "Data/Img/but_un.png"
    data    "Выйти из игры"
    action 3
}

# 4     Start Guess Text
text {
    rect 300 100 680 200
    kind    output
    tex     "Data/Img/win_1.png"
    data    "ERROR"
}

# 5     Guess YES Button
button {
    rect    340 500 300 100
    tex_p  "Data/Img/but_pr.png"
    tex_u  "Data/Img/but_un.png"
    data    "Да"
    action 4
}

# 6     Guess NO Button
button {
    rect    650 500 300 100
    tex_p  "Data/Img/but_pr.png"
    tex_u  "Data/Img/but_un.png"
    data    "Нет"
    action 5
}

# 7     Success To Menu
button {
    rect    650 500 300 100
    tex_p  "Data/Img/but_pr.png"
    tex_u  "Data/Img/but_un.png"
    data    "Да. Все верно"
    action 6
}

# 8     Success To Admin
button {
    rect    340 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Нет. Я загадал другое"
    action 2
}

# 9     Start Exit
button {
    rect    340 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Выход из игры"
    action 3
}

# 10    Start Start Guess
button {
    rect    650 500 300 100
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Начать угадывать"
    action 1
}

# 4     Music Controller
# button {
#     rec
# }

# image {
#     rect 0 0 1280 720
#     data "Data/Img/1.png"
# }
# text {
#     rect    100 500 500 200
#     kind    output
#     tex     "Data/Img/2.png"
#     data    "Приветствую"
# }
# video {
#     rect    100 200 1000 400
#     data    8 "Data/Vid/Back"
#     delay   200
# }
