# 0 Init Text
text {
    rect    300 10 1000 300
    kind    output
    tex     "Data/Img/win.png"
    data    "GraphicKabutoNovel - GKN"
}

# 1 Start Play Text
text {
    rect    300 10 1000 300
    kind    output
    tex     "Data/Img/win.png"
    data    "Привет! $Хочешь начать играть?"
}

# 2 Reserved Text
text {
    rect    300 10 1000 300
    kind    output
    tex     "Data/Img/win.png"
    data    "Тут что то есть"
}

# 3 View Text
text {
    rect    300 10 1000 300
    kind    output
    tex     "Data/Img/win.png"
    data    "Тут что то есть 1"
}

# 4 Choice Text
text {
    rect    300 10 1000 300
    kind    output
    tex     "Data/Img/win.png"
    data    "Тут что то есть 2"
}

# 5 Exit Text
text {
    rect    300 10 1000 300
    kind    output
    tex     "Data/Img/win.png"
    data    "Тут что то есть 3"
}

# 6 Init Img
image {
    rect 500 280 600 300
    data "Data/Img/1.png"
}

# 7 Start Play Img
image {
    rect 500 280 600 300
    data "Data/Img/1.png"
}

# 8 View Img
image {
    rect 500 280 600 500
    data "Data/Img/1.png"
}

# 9 Choice Img
image {
    rect 500 280 600 500
    data "Data/Img/1.png"
}

# 10 Choice 0 Button
button {
    rect    180 660 520 95
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Выбор №1"
    action  6
}

# 11 Choice 1 Button
button {
    rect    900 660 520 95
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Выбор №2"
    action  7
}

# 12 Choice 2 Button
button {
    rect    180 780 520 95
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Выбор №3"
    action  8
}

# 13 Choice 3 Button
button {
    rect    900 780 520 95
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Выбор №4"
    action  9
}

# 14 Background
image {
    rect 0 0 1600 1000
    data "Data/Img/back.png"
}

# 15 Start Button
button {
    rect    930 840 420 120
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Начать игру"
    action  1
}

# 16 Exit Button
button {
    rect    250 840 420 120
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Выйти из игры"
    action  3
}

# 17 Skip Button
button {
    rect    590 840 420 120
    tex_p   "Data/Img/but_pr.png"
    tex_u   "Data/Img/but_un.png"
    data    "Продолжить"
    action  4
}

# 18 Vol Press
button {
    rect    1500 10 90 90
    tex_p   "Data/Img/vol_pr.png"
    tex_u   "Data/Img/vol_un.png"
    switcher
    data    " "
    action  5
}
